---
- hosts: localhost

  vars_files:
    - meraki_vlan_vars.yml
  
  tasks:
    - name: Edit VLAN Settings
      meraki_vlan: 
        auth_key: "{{ meraki_key }}"
        org_name: "{{ Org_Name }}"
        net_name: "{{ Net_Name }}"
        state: "{{ item.state | default('present') }}"
        name: "{{ item.name }}"
        vlan_id: "{{ item.vlan_id }}"
        subnet: "{{ item.subnet }}"
        appliance_ip: "{{ item.appliance_ip }}"
      delegate_to: localhost
      loop: "{{ VLANS }}"
