---
- hosts: localhost

  vars_files:
    - meraki_vlan_vars.yml
  
  tasks:
    - name: Edit VLAN Settings
      cisco.meraki.meraki_mx_vlan: 
        auth_key: "{{ meraki_key }}"
        org_name: "{{ Org_Name }}"
        net_name: "{{ Net_Name }}"
        state: "{{ item.state | default('present') }}"
        name: "{{ item.name }}"
        number: "{{ item.number }}"
        vlan_id: "{{ item.vlan_id }}"
      delegate_to: localhost
      loop: "{{ VLANS }}"
