---
- hosts: localhost

  vars_files:
    - meraki_vars.yml
  
  tasks:
    - name: Query SNMP Settings
      cisco.meraki.meraki_snmp: 
        auth_key: "{{ meraki_key }}"
        org_name: "{{ Org_Name }}"
        state: query
      delegate_to: localhost
