---
- hosts: localhost

  vars_files:
    - meraki_vars.yml
  
  tasks:
    - name: Query configuration templates
      meraki_config_template: 
        auth_key: "{{ meraki_key }}"
        org_name: "{{ Org_Name }}"
        state: query
      delegate_to: localhost
